config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'users/registrations#new'
      get 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'home', to: 'home#index'
    get 'admin', to: 'home#admin'
    get 'user', to: 'users#show'
    root to: 'home#index'

    shallow do
      resources :users do
        resources :contacts, except: %i[index show]
        resources :educations, except: %i[index show]
        resources :personal_details, except: %i[index show]
        resources :projects, except: %i[index show]
        resources :experiences, except: %i[index show]
        resources :skills, except: %i[index show]
        resources :courses, except: %i[index show]
      end
    end
  end
end

app/models/personal_detail.rb
# frozen_string_literal: true

class PersonalDetail < ApplicationRecord
  validates :about, presence: true
  validates :full_name, :position, presence: true, length: { within: 5..50 }

  belongs_to :user
  has_one_attached :photo

  scope :one_record, -> { where(locale: I18n.locale.to_s).last }
end

app/controllers/personal_details_controller.rb
# frozen_string_literal: true

class PersonalDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :define_personal_detail!, except: %i[new create]
  after_action :chenge_full_name, only: %i[create update]

  def new
    @personal_detail = @user.personal_details.build
  end

  def edit; end

  def create
    @personal_detail = @user.personal_details.build personal_detail_params

    if @personal_detail.save
      redirect_to user_path, success: t('flash_plural.new',
                                        model: flash_locale(@personal_detail))
    end

    render :new, status: :unprocessable_entity
  end

  def update
    if @personal_detail.update personal_detail_params
      redirect_to user_path, success: t('flash_plural.update',
                                        model: flash_locale(@personal_detail))
    end

    render :edit, status: :unprocessable_entity
  end

  def destroy
    return unless @personal_detail.destroy

    redirect_to user_path, success: t('flash_plural.destroy',
                                      model: flash_locale(@personal_detail))
  end

  private

  def define_personal_detail!
    @personal_detail = PersonalDetail.find params[:id]
  end

  def personal_detail_params
    params.require(:personal_detail)
          .permit(:photo, :full_name, :position, :about, :locale, :photo)
  end
end

app/helpers/personal_details_helper.rb
# frozen_string_literal: true

module PersonalDetailsHelper
end

app/views/personal_details/_form.html.erb
<%= simple_form_for model, method: method do |f| %>
  <%#= f.file_field :photo, class:"form-control", id: "formFile" %>
  <%= f.input :full_name %>
  <%= f.input :position %>
  <%= f.input :about %>
  <%= f.input :locale, as: :radio_buttons, 
                       collection: Education::VALID_LOCALES, 
                       item_wrapper_class: 'inline' %>
  <%= f.button :submit, f.object.new_record? ? t('submit.create_many', model: i18n_model_name(f.object).downcase) 
                                                : t('submit.edit', model: i18n_model_name(f.object).downcase), 
                                                class: "btn btn-outline-dark my-2 btn-sm" %>
  <%= render 'shared/cancel_button' if f.object.persisted? %>
<% end %> 

app/views/personal_details/_personal_detail.html.erb
<article>
  <%= turbo_frame_tag dom_id(personal_detail) do %>
    <p>
      <%#= image_tag @personal_detail.photo, width: '200px', class: "rounded-circle d-block", style: 'margin-right: auto;
      margin-left: 0;' if @personal_detail.photo.attached? %><br />
    </p>
    <p>
      <strong><i><%= attribute_model(personal_detail, :full_name) %>:</i></strong>
      <%= strip_tags personal_detail.full_name %>
    </p>
    <p>
      <strong><i><%= attribute_model(personal_detail, :position) %>:</i></strong>
      <%= strip_tags personal_detail.position %>
    </p>
    <p>
      <strong><i><%= attribute_model(personal_detail, :about) %>:</i></strong>
      <%= simple_format personal_detail.about, class: 'text-justify' %>
    </p>
    <%= link_to t('link.edit', model: i18n_model_name(personal_detail).downcase), edit_personal_detail_path(personal_detail),
    class: "btn btn-outline-dark mb-4 mx-1" %>
  <% end %>
  <%= button_to t('submit.delete', model: i18n_model_name(personal_detail).downcase), personal_detail_path(personal_detail), 
    method: :delete, class: "btn btn-outline-dark mb-4 mx-1", :onclick => "return confirm('Are you sure?')", :remote => true %>  
</article>

app/views/personal_details/edit.html.erb
<%= turbo_frame_tag dom_id(@personal_detail) do %>
  <div class='my-4 mx-4'>
    <h3 class='md-4'><%= t('user.show.title_edit', model: i18n_model_name(@personal_detail)) %></h3>
    <%= render partial: 'form', locals: { model: @personal_detail, method: :put } %>
  </div>
<% end %>

app/views/personal_details/new.html.erb
<%= turbo_frame_tag dom_id(@personal_detail) do %>
  <div class='my-4 mx-4'>
    <%= render 'shared/go_back_button' %>
    <h3 class='md-4'><%= t('user.show.title_new_many', model: i18n_model_name(@personal_detail).downcase) %></h3>
    <%= render partial: 'form',  locals: { model: [@user, @personal_detail], method: :post } %>
  </div>
<% end %>