config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'users/registrations#new'
      get 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'home', to: 'home#index'
    get 'admin', to: 'home#admin'
    get 'user', to: 'users#show'
    root to: 'home#index'

    shallow do
      resources :users do
        resources :contacts, except: %i[index show]
        resources :educations, except: %i[index show]
        resources :personal_details, except: %i[index show]
        resources :projects, except: %i[index show]
        resources :experiences, except: %i[index show]
        resources :skills, except: %i[index show]
        resources :courses, except: %i[index show]
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  include Locales
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :address, presence: true
  validates :email, presence: true, 'valid_email_2/email': { mx: true }
  validates :telegram, presence: true, format: { with: /\A@.*/ }
  validates :phone, presence: true, length: { maximum: 20 }          
  validates :linkedin, :github, http_url: true

  belongs_to :user

  scope :one_record, -> { where(locale: I18n.locale.to_s).last }
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  validates :coursename, :description, presence: true
  validates :date_of_end, presence: true,
                          format: { with: /\d{4}-\d{2}-\d{2}/ },
                          comparison: { less_than: Date.current }

  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(date_of_end: :desc) }
end

app/models/education.rb
# frozen_string_literal: true

class Education < ApplicationRecord
  validates :name_organization, :degree, :field_of_study, presence: true
  validates :date_of_end, presence: true,
                          format: { with: /\d{4}-\d{2}-\d{2}/ },
                          comparison: { less_than: Date.current }

  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(date_of_end: :desc) }
end

app/models/experience.rb
# frozen_string_literal: true

class Experience < ApplicationRecord
  validates :employer, :position, :description, presence: true
  validates :date_of_begin, presence: true, comparison: { less_than: Date.current }
  validates :date_of_begin, format: { with: /\d{4}-\d{2}-\d{2}/ }
  validates :date_of_end, allow_blank: true, format: { with: /\d{4}-\d{2}-\d{2}/ }
  validate :check_date, if: -> { date_of_end.present? }

  def check_date
    return unless date_of_begin.year > date_of_end.year
    return unless date_of_begin.year == date_of_end.year && 
                  date_of_begin.month > date_of_end.month
    return unless date_of_begin.year == date_of_end.year && 
                  date_of_begin.month == date_of_end.month &&
                  date_of_begin.day > date_of_end.day

    errors.add(:date_of_end, :wrong_date)
  end

  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(date_of_begin: :desc) }
end

app/models/http_url_validator.rb
# frozen_string_literal: true

class HttpUrlValidator < ActiveModel::EachValidator
  def self.compliant?(value)
    uri = URI.parse(value)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end

  def validate_each(record, attribute, value)
    return if value.present? && self.class.compliant?(value)

    record.errors.add(attribute, 'is not a valid HTTP URL')
  end
end

app/models/personal_detail.rb
# frozen_string_literal: true

class PersonalDetail < ApplicationRecord
  validates :about, presence: true
  validates :full_name, :position, presence: true, length: { within: 5..50 }

  belongs_to :user
  has_one_attached :photo

  scope :one_record, -> { where(locale: I18n.locale.to_s).last }
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :description, presence: true
  validates :title, presence: true, length: { within: 3..50 }
  validates :github, presence: true, http_url: true
  validates :site, http_url: true, if: -> { site.present? }

  has_many_attached :previews
  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(created_at: :desc) }
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < ApplicationRecord
  validates :skillname, presence: true, length: { within: 3..50 }

  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(:created_at) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: { admin: 0 }, _suffix: :role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :personal_details, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :skills, dependent: :destroy
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :define_variables!

  def index; end

  def admin
    render :index
  end

  private

  def define_variables!
    @contact = Contact.one_record if Contact.any?
    @pagy_project, @projects = pagy Project.meny_records, items: 3, page_param: :pagy_project
    @pagy_experience, @experiences = pagy Experience.meny_records, items: 2, page_param: :pagy_experience
    @educations = Education.meny_records
    @personal_details = PersonalDetail.one_record.decorate if PersonalDetail.any?
    @pagy_skill, @skills = pagy Skill.meny_records, items: 4, page_param: :pagy_skill
    @pagy_course, @courses = pagy Course.meny_records, items: 5, page_param: :pagy_course

    @user = User.last
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def pagination(obj)
    pagy_bootstrap_nav(obj) if obj.pages > 1
  end

  def i18n_model_name(model, count: 1)
    model.model_name.human(count: count)
  end

  def attribute_model(model, attr)
    model.class.human_attribute_name(attr)
  end

  def full_title(page_title = '')
    base_title = t('site_name')
    page_title ? "#{page_title} | #{base_title}" : base_title.to_s
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: { current_page: current_page }
  end

  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page
    css_text = current_page == title ? 'text-success' : 'text-black'
    options[:class] = if options[:class]
                        "#{options[:class]} #{css_text}"
                      else
                        css_text
                      end

    link_to title, url, options
  end
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/helpers/educations_helper.rb
# frozen_string_literal: true

module EducationsHelper
end

app/helpers/experiences_helper.rb
# frozen_string_literal: true

module ExperiencesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/skills_helper.rb
# frozen_string_literal: true

module SkillsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <div class='wrapper'>
      <%= yield :main_menu %>
      
      <main class='container content'>
        <% flash.each do |type, msg| %>    
          <!-- Change flash messages of devise to bootstrap format -->
          <% case type %>
          <% when 'alert'%>
            <% type = 'danger' %>
          <% when 'notice' %>
            <% type = 'success' %>
          <% end %>

          <%= tag.div msg, class: "alert alert-#{type} text-center", role: 'alert' %>
        <% end %>

        <%= yield %>
      </main>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_admin.html.erb
<% unless user_signed_in? %>
  <li class="nav-item">
    <%= nav_tab t('menu.sign_up'), sign_up_path, class: "nav-link", 
      current_page: current_page unless @user.present? %>
  </li>
  <li class="nav-item">
    <%= nav_tab t('menu.sign_in'), sign_in_url, class: "nav-link", 
      current_page: current_page unless current_user %>
  </li>
<% end %>

app/views/shared/_cancel_button.html.erb
<%= link_to t("submit.cancel"), user_path, class: "btn btn-outline-dark btn-sm" %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg bg-light mt-4 footer">
  <div class="container ps-5 text-center">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <time datetime='<%= Time.now.year %>' class="nav-link"><%= Time.now.year %></time>
        </li>
        <li class="nav-item">
          <%= link_to sanitize(t('footer.telegram')), 'https://t.me/elenkasu', 
            class: "nav-link", target: :_blank %>           
        </li>
      </ul>
    </div>
  </div>
</nav>  

app/views/shared/_go_back_button.html.erb
<%= link_to sanitize(t('submit.go_back')), user_path, class: "btn btn-outline-dark mb-4 btn-sm", role: 'button' %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% unless user_signed_in? %>
            <li class="nav-item">
              <%= nav_tab t('menu.owner'), admin_path, role: 'button', 
                class: "nav-link", current_page: current_page if controller_name == 'home' && action_name == 'index' %>     
            </li>
            <% if action_name == 'admin' || ['sessions', 'registrations'].include?(controller_name) %>
              <%= render partial: 'shared/admin', locals: { current_page: current_page } %>
            <% end %>
          <% else %>
            <li class="nav-item">
              <%= nav_tab t('menu.main_page'), root_path, class: "nav-link", 
                style: 'padding-left: 40px;', current_page: current_page %>
            </li>
            <li class="nav-item">
              <%= nav_tab t('menu.admin_page'), user_path, class: "nav-link", current_page: current_page if policy(current_user).show? %>
            </li>      
            <li class="nav-item">
              <%= nav_tab t('menu.sign_out'), sign_out_path, 'data-turbo_method': :delete, 
              :onclick => "return confirm('Are you sure?')", :remote => true, class: "nav-link",
              current_page: current_page %>
            </li>
          <% end %>
        </ul>
        <ul class='nav mb-md-0'>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= t('submit.language') %>
            </a>
            <ul class="dropdown-menu text-center">
              <li class="nav-item">
                <%= link_to 'English', controller: controller_name, 
                    action: action_name, locale: :en, class: "dropdown-item" %>
              </li>
              <li><hr class='dropdown-divider'></li>
              <li class="nav-item">
                <%= link_to 'Русский', controller: controller_name, 
                    action: action_name, locale: :ru, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>  
  </header>
<% end %>