config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'users/registrations#new'
      get 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'home', to: 'home#index'
    get 'admin', to: 'home#admin'
    get 'user', to: 'users#show'
    root to: 'home#index'

    shallow do
      resources :users do
        resources :contacts, except: %i[index show]
        resources :educations, except: %i[index show]
        resources :personal_details, except: %i[index show]
        resources :projects, except: %i[index show]
        resources :experiences, except: %i[index show]
        resources :skills, except: %i[index show]
        resources :courses, except: %i[index show]
      end
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :description, presence: true
  validates :title, presence: true, length: { within: 3..50 }
  validates :github, presence: true, http_url: true
  validates :site, http_url: true, if: -> { site.present? }

  has_many_attached :previews
  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(created_at: :desc) }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :define_project!, except: %i[new create]

  def new
    @project = @user.projects.build
  end

  def edit; end

  def create
    @project = @user.projects.build(project_params)

    if @project.save
      return redirect_to user_path, success: t('flash.new',
                                               model: flash_locale(@project))

    end

    render :new, status: :unprocessable_entity
  end

  def update
    if @project.update(project_params)
      redirect_to user_path, success: t('flash.update',
                                        model: flash_locale(@project))
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    return unless @project.destroy

    redirect_to user_path, success: t('flash.destroy',
                                      model: flash_locale(@project))
  end

  private

  def define_project!
    @project = Project.find params[:id]
  end
  
  def project_params
    params.require(:project)
          .permit(:title, :site, :github, :description, :locale, previews: [])
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for model, method: method, multiple: true do |f| %>
  <%= f.input :title%>
  <%#= f.file_field :previews, multiple: true, class:"form-control", id: "formFile" %>
  <%= f.input :site %>
  <%= f.input :github %>
  <%= f.input :description %>
  <%= f.input :locale, as: :radio_buttons, 
                       collection: Education::VALID_LOCALES, 
                       item_wrapper_class: 'inline' %>
  <%= f.button :submit, f.object.new_record? ? t('submit.create_one', model: i18n_model_name(f.object).downcase) 
                                                : t('submit.edit', model: i18n_model_name(f.object).downcase), 
                                                class: "btn btn-outline-dark my-2 btn-sm" %>
  <%= render 'shared/cancel_button' if f.object.persisted? %>
<% end %> 

app/views/projects/_project.html.erb
<article class='col my-4'>
  <%= turbo_frame_tag dom_id(project) do %>
    <p class='project_title'>
      <strong><i><%= strip_tags project.title %></i></strong><br />
    </p>
    <p>
      <% unless project.site.blank? %>
        <strong><i><%= attribute_model(project, :site) %>:</i></strong>
        <%= link_to project.site, "#{project.site}", class: 'text-dark text-decoration-none', target: :_blank %>
      <% end %>
    </p>
    <p>
      <strong><i><%= attribute_model(project, :github) %>:</i></strong>
      <%= link_to project.github, "#{project.github}", class: 'text-dark text-decoration-none', target: :_blank %>
    </p>
    <p><strong><i><%= attribute_model(project, :description) %></i></strong>:</p>
    <p class='taxt-justify'><%= project.description %></p>
    <%# if project.previews.attached? %>
      <%# project.previews.each do |img| %>
      <%# <div class='img_block'> %>
        <%#= image_tag img, class: "d-block img" %>
      <%# </div> %>
      <%# end %>
    <%# end %>
    <%= link_to t('link.edit', model: i18n_model_name(project).downcase), edit_project_path(project),
    class: "btn btn-outline-dark mb-4 mx-1" %>
  <% end %>
  <%= button_to t('submit.delete', model: i18n_model_name(project).downcase), project_path(project), 
    method: :delete, class: "btn btn-outline-dark mb-4 mx-1", :onclick => "return confirm('Are you sure?')", :remote => true %>
</article>

app/views/projects/edit.html.erb
<%= turbo_frame_tag dom_id(@project) do %>
  <div class='my-4 mx-4'>
    <h3 class='md-4'><%= t('user.show.title_edit', model: i18n_model_name(@project)) %></h3>
    <%= render partial: 'form', locals: { model: @project, method: :put } %>
  </div>
<% end %>

app/views/projects/new.html.erb
<%= turbo_frame_tag dom_id(@project) do %>
  <div class='col-6 my-4 mx-4'>
    <%= render 'shared/go_back_button' %>
    <h3 class='md-4'><%= t('user.show.title_new_one', model: i18n_model_name(@project).downcase) %></h3>
    <%= render partial: 'form',  locals: { model: [@user, @project], method: :post } %>
  </div>
<% end %>