config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }

    devise_scope :user do
      get 'sign_in', to: 'devise/sessions#new'
      get 'sign_up', to: 'users/registrations#new'
      get 'sign_out', to: 'devise/sessions#destroy'
    end

    get 'home', to: 'home#index'
    get 'admin', to: 'home#admin'
    get 'user', to: 'users#show'
    root to: 'home#index'

    shallow do
      resources :users do
        resources :contacts, except: %i[index show]
        resources :educations, except: %i[index show]
        resources :personal_details, except: %i[index show]
        resources :projects, except: %i[index show]
        resources :experiences, except: %i[index show]
        resources :skills, except: %i[index show]
        resources :courses, except: %i[index show]
      end
    end
  end
end

app/models/experience.rb
# frozen_string_literal: true

class Experience < ApplicationRecord
  validates :employer, :position, :description, presence: true
  validates :date_of_begin, presence: true, comparison: { less_than: Date.current }
  validates :date_of_begin, format: { with: /\d{4}-\d{2}-\d{2}/ }
  validates :date_of_end, allow_blank: true, format: { with: /\d{4}-\d{2}-\d{2}/ }
  validate :check_date, if: -> { date_of_end.present? }

  def check_date
    return unless date_of_begin.year > date_of_end.year
    return unless date_of_begin.year == date_of_end.year && 
                  date_of_begin.month > date_of_end.month
    return unless date_of_begin.year == date_of_end.year && 
                  date_of_begin.month == date_of_end.month &&
                  date_of_begin.day > date_of_end.day

    errors.add(:date_of_end, :wrong_date)
  end

  belongs_to :user

  scope :meny_records, -> { where(locale: I18n.locale.to_s).order(date_of_begin: :desc) }
end

app/controllers/experiences_controller.rb
# frozen_string_literal: true

class ExperiencesController < ApplicationController
  before_action :authenticate_user!
  before_action :define_experience!, except: %i[new create]

  def new
    @experience = @user.experiences.build
  end

  def edit; end

  def create
    @experience = @user.experiences.build experience_params

    if @experience.save
      redirect_to user_path, success: t('flash.new',
                                        model: flash_locale(@experience))
    end

    render :new, status: :unprocessable_entity
  end

  def update
    if @experience.update experience_params
      redirect_to user_path, success: t('flash.update',
                                        model: flash_locale(@experience))
    end

    render :edit, status: :unprocessable_entity
  end

  def destroy
    return unless @experience.destroy

    redirect_to user_path, success: t('flash.destroy',
                                      model: flash_locale(@experience))
  end

  private

  def define_experience!
    @experience = Experience.find params[:id]
  end

  def experience_params
    params.require(:experience).permit(:employer, :position, :date_of_begin,
                                       :date_of_end, :description, :locale)
  end
end

app/helpers/experiences_helper.rb
# frozen_string_literal: true

module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<article class='col my-4'>
  <%= turbo_frame_tag dom_id(experience) do %>
    <p>
      <strong><i><%= attribute_model(experience, :employer) %>:</i></strong>
      <%= strip_tags experience.employer %>
    </p>
    <p>
      <strong><i><%= attribute_model(experience, :position) %>:</i></strong>
      <%= strip_tags experience.position %>
    </p>
    <p>
      <strong><i><%= attribute_model(experience, :date_of_begin) %>:</i></strong>
      <%= I18n.l(experience.date_of_begin, format: '%B %Y') %>
    </p>
    <p>
      <strong><i><%= attribute_model(experience, :date_of_end) %>:</i></strong>
      <%= experience.date_of_end.blank? ? t('user.show.blank_yaer_ending_experience') : I18n.l(experience.date_of_end, format: '%B %Y') %>
    </p>
    <p>
      <strong><i><%= attribute_model(experience, :description) %>:</i></strong><br />
      <%= simple_format experience.description, class: 'text-justify' %>
    </p>
    <%= link_to t('link.edit', model: i18n_model_name(experience).downcase), edit_experience_path(experience),
    class: "btn btn-outline-dark mb-4 mx-1" %>
  <% end %>
  <%= button_to t('submit.delete', model: i18n_model_name(experience).downcase), experience_path(experience), 
   method: :delete, class: "btn btn-outline-dark mb-4 mx-1", :onclick => "return confirm('Are you sure?')", :remote => true %>  
</article>

app/views/experiences/_form.html.erb
<%= simple_form_for model, method: method do |f| %>
  <%= f.input :employer %>
  <%= f.input :position %>                            
  <%= f.input :date_of_begin, as: :date, start_year: Date.today.year - 60,
                                        end_year: Date.today.year,
                                        order: [ :day, :month, :year] %>
  <%= f.input :date_of_end, as: :date, start_year: Date.today.year - 60,
                                        end_year: Date.today.year,
                                        order: [ :day, :month, :year] %>
  <%= f.input :description %>
  <%= f.input :locale, as: :radio_buttons, 
                       collection: Education::VALID_LOCALES, 
                       item_wrapper_class: 'inline' %>
  <%= f.button :submit, f.object.new_record? ? t('submit.create_one', model: i18n_model_name(f.object).downcase) 
                                                : t('submit.edit', model: i18n_model_name(f.object).downcase), 
                                                class: "btn btn-outline-dark my-2 btn-sm" %>
  <%= render 'shared/cancel_button' if f.object.persisted? %>
<% end %>

app/views/experiences/edit.html.erb
<%= turbo_frame_tag dom_id(@experience) do %>
  <div class='my-4 mx-4'>
    <h3 class='md-4'><%= t('user.show.title_edit', model: i18n_model_name(@experience)) %></h3>
    <%= render partial: 'form', locals: { model: @experience, method: :put } %>
  </div>
<% end %>

app/views/experiences/new.html.erb
<%= turbo_frame_tag dom_id(@experience) do %>
  <div class='col-6 my-4 mx-4'>
    <%= render 'shared/go_back_button' %>
    <h3 class='md-4'><%= t('user.show.title_new_many', model: i18n_model_name(@experience).downcase) %></h3>
    <%= render partial: 'form',  locals: { model: [@user, @experience], method: :post } %>
  </div>
<% end %>